version: "3.9"
services:
  app:
    image: "gennadiyggman/landing-app:latest"
    container_name: app
    restart: unless-stopped
    ports:
      - "3000:3000"   # проксирование порта приложения
    # приложение находится в одной сети с Prometheus/Grafana (default network)

  prometheus:
    image: "prom/prometheus:latest"
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"   # веб-интерфейс Prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro   # конфиг Prometheus
      - prometheus_data:/prometheus                         # (опционально) хранилище с данными

  grafana:
    image: "grafana/grafana:latest"
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  prometheus_data:
